# -*- coding: utf-8 -*-
"""VaR Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wEBx8i552idRCKmyPSwO95RzPhFWlXn
"""

import numpy as np
import pandas as pd
import yfinance as yf
from scipy.stats import norm

stocks = ['NVDA', 'AAPL']
start_date = '2020-01-01'
end_date = '2025-01-01'

portfolio_value = 100000
weights = np.array([0.5, 0.5])
confidence_level = 0.95
num_simulations = 10000

data = yf.download(stocks, start=start_date, end=end_date)['Close']


returns = data.pct_change().dropna()

portfolio_returns = returns.dot(weights)

mean = portfolio_returns.mean()
std = portfolio_returns.std()

z_score = norm.ppf(1 - confidence_level)

parametric_var = portfolio_value * (-(mean + z_score * std))

historical_var = portfolio_value * -np.percentile(
    portfolio_returns, (1 - confidence_level) * 100
)

simulated_returns = np.random.normal(mean, std, num_simulations)

monte_carlo_var = portfolio_value * -np.percentile(
    simulated_returns, (1 - confidence_level) * 100
)

print("\n===== VALUE AT RISK (VaR) =====")
print(f"Portfolio Value: ${portfolio_value:,.0f}")
print(f"Confidence Level: {confidence_level*100:.0f}%\n")

print(f"Parametric VaR:   ${parametric_var:,.2f}")
print(f"Historical VaR:   ${historical_var:,.2f}")
print(f"Monte Carlo VaR:  ${monte_carlo_var:,.2f}")