# -*- coding: utf-8 -*-
"""VaR Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wEBx8i552idRCKmyPSwO95RzPhFWlXn
"""

import numpy as np
import pandas as pd
import yfinance as yf
from scipy.stats import norm

# -----------------------------------
# SETTINGS
# -----------------------------------
stocks = ['NVDA', 'AAPL']   # NVIDIA and Apple
start_date = '2020-01-01'
end_date = '2025-01-01'

portfolio_value = 100000    # Initial investment ($)
weights = np.array([0.5, 0.5])  # Portfolio weights
confidence_level = 0.95
num_simulations = 10000


# -----------------------------------
# 1. DOWNLOAD DATA
# -----------------------------------
data = yf.download(stocks, start=start_date, end=end_date)['Close']

# Calculate daily returns
returns = data.pct_change().dropna()

# Portfolio returns
portfolio_returns = returns.dot(weights)


# -----------------------------------
# 2. PARAMETRIC VaR
# -----------------------------------
mean = portfolio_returns.mean()
std = portfolio_returns.std()

z_score = norm.ppf(1 - confidence_level)

parametric_var = portfolio_value * (-(mean + z_score * std))


# -----------------------------------
# 3. HISTORICAL VaR
# -----------------------------------
historical_var = portfolio_value * -np.percentile(
    portfolio_returns, (1 - confidence_level) * 100
)


# -----------------------------------
# 4. MONTE CARLO VaR
# -----------------------------------
simulated_returns = np.random.normal(mean, std, num_simulations)

monte_carlo_var = portfolio_value * -np.percentile(
    simulated_returns, (1 - confidence_level) * 100
)


# -----------------------------------
# 5. RESULTS
# -----------------------------------
print("\n===== VALUE AT RISK (VaR) =====")
print(f"Portfolio Value: ${portfolio_value:,.0f}")
print(f"Confidence Level: {confidence_level*100:.0f}%\n")

print(f"Parametric VaR:   ${parametric_var:,.2f}")
print(f"Historical VaR:   ${historical_var:,.2f}")
print(f"Monte Carlo VaR:  ${monte_carlo_var:,.2f}")